[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std"]
description = "Real Time For the Masses (RTFM) framework for ARM Cortex-M microcontrollers"
documentation = "https://japaric.github.io/cortex-m-rtfm/cortex_m_rtfm/"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.3.4"

[dependencies]
cortex-m = "0.5.7"
cortex-m-rtfm-macros = { path = "macros", version = "0.3.2" }
rtfm-core = "0.2.0"
untagged-option = "0.1.1"

[target.'cfg(target_arch = "x86_64")'.dev-dependencies]
compiletest_rs = "0.3.14"

[dev-dependencies]
cortex-m-rt = "0.6.4"
cortex-m-rt-macros = "0.1.2"
panic-halt = "0.2.0"

[dev-dependencies.stm32f103xx]
features = ["rt"]
version = "0.10.0"

[features]
cm7-r0p1 = ["cortex-m/cm7-r0p1"]

[profile.release]
lto = true
